<?php $this->headTitle('Добавить') ?>


	<h1><?php echo $this->escapeHtml("Добавить новой страницы") ?></h1>


<?php $form->setAttribute('action', $this->url('page', array('action'=>'add'))) ?>
<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>
<!--устанавливаем action формы-->
<dl class="zend_form">
	<dt><?= $this->formLabel($form->get('title')) ?></dt>
	<dd>
		<?= $this->formElement($form->get('title')) ?>
		<?= $this->formElementErrors($form->get('title'),array('class'=>'error')) ?>
	</dd>
	<br>
	<dt><?= $this->formLabel($form->get('article')) ?></dt>
	<dd>
		<?= $this->formElement($form->get('article')) ?>
		<?= $this->formElementErrors($form->get('article'), array('class'=>'error')) ?>
	</dd>
	<br>
	<dt><?= $this->formLabel($form->get('pub')) ?></dt>
	<dd>
		<?= $this->formElement($form->get('pub')) ?>
		<?= $this->formElementErrors($form->get('pub'), array('class'=>'error')) ?>
	</dd>
	<br>
	<dt>
		<?= $this->formSubmit($form->get('submit')) ?>
	</dt>
	<?= $this->form()->closeTag() ?>
</dl>
