<?php $this->headTitle('Добавить') ?>
<div class="add_new">
	<nav>
		<ul>
			<li>
				<a href='<?=$this->url('admin-panel')?>'>&larr;&nbsp;админ панель</a>
			</li>
			<li>/</li>
			<li>добавить</li>
		</ul>
	</nav>
	<div class="clear"></div>
	<dl class="form-group">
		<?php $form->prepare()?>
		<?=$this->form()->openTag($form)?>
		<dt><?=$this->formLabel($form->get('title'))?></dt>
		<dd>
			<?=$this->formElement($form->get('title'))?>
			<?=$this->formElementErrors($form->get('title'),array('style'=>'color:red'))?>
		</dd>
		<dt>
			<?=$this->formLabel($form->get('content'))?><span id="question">?</span>
		<div id="question_answer">
			<div  id="close">закрыть</div>
			<ul>
				<li>Для вставки тега (читать подробнее) вставьте в текст [/more/]</li>
				<li>
					<img id="loading" style="display: none" src='<?=$this->basePath().'/img/loading.gif'?>'>
					<span id="link_click">Доступные файлы на сервере</span>
					<div id="container_img">
						<input type="file" id="file" name="file_name" accept="image/*">
						<div id="upload">Загрузить</div>
						<div class="clear"></div>
						<div id="images">
							<ul>
								<?php foreach($files as $file):?>
									<li>
										<a target="_blank" href="<?=$this->basePath()."/files_upload/{$file}"?>"><?=$this->basePath()."http://adm.moiro/moiro/public/files_upload/{$file}"?></a>&nbsp;&nbsp;
										<img class="delete" data-name="<?=$file?>" src='<?=$this->basePath()
										.'/img/delete.png'?>'>
									</li>
								<?php endforeach; ?>
							</ul>
						</div>
					</div>
				</li>
			</ul>
		</div>
		</dt>
		<dd>
			<?=$this->formElement($form->get('content'))?>
			<?=$this->formElementErrors($form->get('content'),array('style'=>'color:red'))?>
		</dd>

		<dt><?=$this->formElement($form->get('submitAddNews'))?><dt>
			<?=$this->form()->closeTag()?>
	</dl>
</div>

