<?php $this->headTitle('Панель управления') ?>
<div class="news">
	<div class="add_news" >
		<a href='<?=$this->url('admin-panel', array('action'=>'add'))?>'>&plus;&nbsp;добавить новость</a>
	</div>
	<?php foreach ($this->paginator as $new) : // <-- change here! ?>
		<div class="new">
			<header>
				<h1><?=$new->title?></h1>
			</header>
			<section>
				<header>
					<h1>опубликовано:&nbsp;<code><?=$new->date?></code></h1>
				</header>
				<article>
					<p><?=$new->content?></p>
					<p><a href="<?=$this->url('admin-panel', array('action'=>'more-info',
							'id'=>$new->id_new))?>">читать&nbsp;подробнее&nbsp;&rarr;</a></p>
					<p>|&nbsp;<a href='<?=$this->url('admin-panel', array('action'=>'edit',
							'id'=>$new->id_new))?>'>редактировать</a>&nbsp;|&nbsp;<a href='<?=$this->url
						('admin-panel', array('action'=>'delete', 'id'=>$new->id_new))?>'>удалить</a>&nbsp;|</p>
				</article>
			</section>
		</div>
	<?php endforeach; ?>
</div>
<?=$this->paginationControl(
	$this->paginator,
	'Sliding',
	array('partial/paginator.phtml', 'News'),
	// the route to link to when a user clicks a control link
	array(
		'route' => 'admin-panel'
	)
); ?>