<?php $this->layout()->active_page = 'admin' ?>
<div class="news">
	<div class="add_news" >
		<a href="">Добавить новость</a>
	</div>
	<?php foreach($news as $new): ?>
		<div class="new">
			<header>
				<h1><?=$new->title?></h1>
			</header>
			<section>
				<header>
					<h1>Опубликовано:&nbsp;<code><?=$new->date?></code></h1>
				</header>
				<article>
					<p><?=$new->content?></p>
					<p>|&nbsp;<a href="<?=$this->url('news', array('action'=>'more-info',
							'id'=>$new->id_new))?>">Редактировать</a>&nbsp;|&nbsp;<a href="<?=$this->url('news',
							array('action'=>'more-info',
							'id'=>$new->id_new))?>">Удалить</a>&nbsp;|</p>
				</article>
			</section>
		</div>
	<?php endforeach; ?>
</div>