<div class="news">
	<div class="add_news" >
		<a href='<?=$this->url('admin-panel', array('action'=>'add'))?>'>&plus;&nbsp;добавить новость</a>
	</div>
	<div class="new">
		<p><a href="<?=$this->url('admin-panel')?>">&larr;&nbsp;вернуться&nbsp;к&nbsp;новостям</a></p>
		<header>
			<h1><?=$new->title?></h1>
		</header>
		<section>
			<header>
				<h1>опубликовано:&nbsp;<?=$new->date?></h1>
			</header>
			<article>
				<p><?=$new->content?></p>
				<p><a href="<?=$this->url('admin-panel', array('action'=>'more-info',
						'id'=>$new->id_new))?>">читать&nbsp;подробнее&nbsp;&rarr;</a></p>
				<p>|&nbsp;<a href='<?=$this->url('admin-panel', array('action'=>'edit',
						'id'=>$new->id_new))?>'>редактировать</a>&nbsp;|&nbsp;<a href='<?=$this->url('admin-panel',
						array('action'=>'delete', 'id'=>$new->id_new))?>'>удалить</a>&nbsp;|</p>
			</article>
			</article>
		</section>
		<p><a href="<?=$this->url('admin-panel')?>">&larr;&nbsp;веруться&nbsp;к&nbsp;новостям</a></p>
	</div>
</div>