<div class="news">
	<?php foreach($new as $new): ?>
		<div class="new">
			<p class="glyphicon-bullhorn"><a href="<?=$this->url('news')?>">&nbsp;Вернуться&nbsp;к&nbsp;новостям</a></p>
			<header>
				<h1><?=$new->title?></h1>
			</header>
			<section>
				<header>
					<h1>Опубликовано:&nbsp;<code><?=$new->date?></code></h1>
				</header>
				<article>
					<p><?=$new->content?></p>
				</article>
			</section>
			<p class="glyphicon-bullhorn"><a href="<?=$this->url('news')?>">&nbsp;Вернуться&nbsp;к&nbsp;новостям</a></p>
		</div>
	<?php endforeach; ?>
</div>