<div class="news">
	<div class="new">
		<p><a href="<?=$this->url('news')?>">&larr;&nbsp;вернуться&nbsp;к&nbsp;новостям</a></p>
		<header>
			<h1><?=$new->title?></h1>
		</header>
		<section>
			<header>
				<h1>опубликовано:&nbsp;<code><?=$new->date?></code></h1>
			</header>
			<article>
				<p><?=$new->content?></p>
			</article>
		</section>
		<p><a href="<?=$this->url('news')?>">&larr;&nbsp;вернуться&nbsp;к&nbsp;новостям</a></p>
	</div>
</div>