<?=$this->doctype(); ?>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<?=$this->headTitle('МОИРО ЦЕНТР ИНФОРМАТИЗАЦИИ')->setSeparator(' - ')->setAutoEscape(true)?>
	<?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>
	<!-- Le styles -->
	<?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
		'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
		->prependStylesheet($this->basePath() . '/js/cleditor1_4_4/jquery.cleditor.css') ?>

	<!-- Scripts -->
	<?=$this->headScript()
		->prependFile($this->basePath() . '/js/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/jquery.min.js')
		->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
		->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9'))
		->appendFile($this->basePath() . '/js/cleditor1_4_4/jquery.cleditor.min.js',   'text/javascript'); ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li<?=isset($this->active_page)&&$this->active_page==='home'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('home') ?>">ГЛАВНАЯ</a>
				</li>
				<li<?=isset($this->active_page)&&$this->active_page==='news'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('news') ?>">НАШИ НОВОСТИ</a>
				</li>
				<li<?=isset($this->active_page)&&$this->active_page==='aboutus'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('aboutus') ?>">О НАС</a>
				</li>
				<li<?=isset($this->active_page)&&$this->active_page==='contacts'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('contacts') ?>">КОНТАКТЫ</a>
				</li>
				<?php if(isset($admin)): ?>
					<li<?=isset($this->active_page)&&$this->active_page==='admin'?' class="active admin_nav"':'
				class="admin_nav"'?>>
						<a href="<?php echo $this->url('admin-panel') ?>">УПРАВЛЕНИЕ НОВОСТЯМИ</a>
					</li>
					<li class="admin_nav">
						<a  href="<?php echo $this->url('admin',array('action'=>'logout')) ?>">ВЫХОД</a>
					</li>
				<?php endif ?>

			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
<div class="container min">
	<?php echo $this->content; ?>
</div> <!-- /container -->
<footer class="modal-footer down">
	<p>&copy; <?=date("Y")?> Минский областной институт развития образования</p>
	<p>Центр информатизации образования</p>
	<p><a href="mailto:adm@moiro.by" >adm@moiro.by</a></p>
	<p><a href="http://moiro.by/" target="_blank">http://moiro.by</a></p>
</footer>
</body>
<?=$this->inlineScript()->setScript('(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter22965625 = new Ya.Metrika({id:22965625,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
		d.addEventListener("DOMContentLoaded", f, false);
	} else { f(); }
})(document, window, "yandex_metrika_callbacks");')->appendFile('http://consultsystems.ru/script/17620/',
	'text/javascript', 'charset="utf-8"')->appendFile($this->basePath() . '/js/jquery.snow.min.1.0.js')->appendFile($this->basePath() . '/js/jquery.snow.min.1.0.js'); ?>
<script type="application/javascript">
	$(document).ready( function(){
		$.fn.snow({ minSize: 5, maxSize: 50, newOn: 1000, flakeColor: '#0099FF' });

		$.cleditor.defaultOptions.width = 200;
		$.cleditor.defaultOptions.height = 100;

		$("#content").cleditor({
			width: '100%', // width not including margins, borders or padding
			height: 250, // height not including margins, borders or padding
			controls: // controls to add to the toolbar
			"bold italic underline strikethrough subscript superscript | font size " +
			"style | color highlight removeformat | bullets numbering | outdent " +
			"indent | alignleft center alignright justify | undo redo | " +
			"rule image link unlink | cut copy paste pastetext | print source",
			colors: // colors in the color popup
			"FFF FCC FC9 FF9 FFC 9F9 9FF CFF CCF FCF " +
			"CCC F66 F96 FF6 FF3 6F9 3FF 6FF 99F F9F " +
			"BBB F00 F90 FC6 FF0 3F3 6CC 3CF 66C C6C " +
			"999 C00 F60 FC3 FC0 3C0 0CC 36F 63F C3C " +
			"666 900 C60 C93 990 090 399 33F 60C 939 " +
			"333 600 930 963 660 060 366 009 339 636 " +
			"000 300 630 633 330 030 033 006 309 303",
			fonts: // font names in the font popup
			"Arial,Arial Black,Comic Sans MS,Courier New,Narrow,Garamond," +
			"Georgia,Impact,Sans Serif,Serif,Tahoma,Trebuchet MS,Verdana",
			sizes: // sizes in the font size popup
				"1,2,3,4,5,6,7",
			styles: // styles in the style popup
				[["Paragraph", "<p>"], ["Header 1", "<h1>"], ["Header 2", "<h2>"],
					["Header 3", "<h3>"],  ["Header 4","<h4>"],  ["Header 5","<h5>"],
					["Header 6","<h6>"]],
			useCSS: false, // use CSS to style HTML when possible (not supported in ie)
			docType: // Document type contained within the editor
				'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">',
			docCSSFile: // CSS file used to style the document contained within the editor
				"",
			bodyStyle: // style to assign to document body contained within the editor
				"margin:4px; font:10pt Arial,Verdana; cursor:text"
		});
	});
</script>
</html>
