<?=$this->doctype(); ?>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<?=$this->headTitle('МОИРО ЦЕНТР ИНФОРМАТИЗАЦИИ')->setSeparator(' - ')->setAutoEscape(true)?>

	<?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

	<!-- Le styles -->
	<?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
		'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

	<!-- Scripts -->
	<?=$this->headScript()
		->prependFile($this->basePath() . '/js/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/jquery.min.js')
		->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
		->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9')); ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>

		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li<?=isset($this->active_page)&&$this->active_page==='home'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('home') ?>">ГЛАВНАЯ</a>
				</li>
				<li<?=isset($this->active_page)&&$this->active_page==='aboutus'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('aboutus') ?>">О НАС</a>
				</li>
				<li<?=isset($this->active_page)&&$this->active_page==='contacts'?' &nbsp; class="active"':null?>>
					<a href="<?php echo $this->url('contacts') ?>">КОНТАКТЫ</a>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>
<div class="container min">
	<?php echo $this->content; ?>
</div> <!-- /container -->
<footer class="modal-footer down">
	<p>&copy; <?=date("Y")?> Минский областной институт развития образования</p>
	<p>Центр информатизации образования</p>
	<p><a href="mailto:adm@moiro.by" >adm@moiro.by</a></p>
	<p><a href="http://moiro.by/" target="_blank">http://moiro.by</a></p>
</footer>
</body>

<?=$this->inlineScript()->setScript('(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter22965625 = new Ya.Metrika({id:22965625,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
		d.addEventListener("DOMContentLoaded", f, false);
	} else { f(); }
})(document, window, "yandex_metrika_callbacks");'); ?>
</html>
