<?php $this->layout()->active_page = 'contacts' ?>
<?php $this->headTitle('КОНТАКТЫ') ?>

<div class="contacts">
	<div class="text_contact">
		<fieldset>
			<legend>Наши контакты:</legend>
			<address>220104, г. Минск, ул. П. Глебки, 88</address>
			<p>Тел/факс:<a href="tel:"> 216 97 10</a></p>
			<p>E-mail:<a href="mailto:mail@moiro.by">mail@moiro.by</a></p>
		</fieldset>

		<fieldset>
			<legend>Наши реквизиты для оплаты платных услуг:</legend>
			<p>В квитанции об оплате в графе «назначение платежа» указать наименование платной услуги и Ф.И.О. плательщика
				Полное наименование	ГУО «Минский областной институт развития образования»</p>

			<p>Банковские реквизиты: р/с <strong>3632632760001</strong> филиал 527 «Белжелдор»<br>
				АСБ «Беларусбанк» код 254, ул. Воронянского, 7а УНП 101077412 ОКПО 37396062</p>
		</fieldset>
	</div>

	<div class="yandex_map">
		<h1>Мы на яндекс карте</h1>
		<script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1
		.0/js/?sid=dTWqgNwRoyoaFxtUY5O15uxckkKLnb80&width=600&height=310"></script>
	</div>
</div>
