<?php $this->layout()->active_page = 'Home' ?>

<div class="hovergallery">
	<a href = "http://adm.moiro.by/courses"><img src="/start.moiro/public/img/courses.gif" title = "курсы" /></a>
	<a href = "http://adm.moiro.by/kadrs"><img src="/start.moiro/public/img/kadrs.gif" title = "кадры" /></a>
	<a href = "http://adm.moiro.by/visiting"><img src="/start.moiro/public/img/visiting.gif" title = "пропуски" /></a>
	<a href = "http://adm.moiro.by/moodle"><img src="/start.moiro/public/img/moodle.gif" title = "дистанционное обучение" /></a>
	<a href = "http://adm.moiro.by/wunderkind"><img src="/start.moiro/public/img/wunderkind.gif" title = "олимпиады" /></a>
	<a href = "http://adm.moiro.by/dnevnik"><img src="/start.moiro/public/img/dnevnik.gif" title = "электронный дневник" /></a>

	<a href = "http://sert.moiro.by"><img src="/start.moiro/public/img/sertifikacya.gif" title = "сертификация" /></a>
	<a href = "http://profteh.moiro.by"><img src="/start.moiro/public/img/profteh.gif" title = "профтех" /></a>
	<a href="/start.moiro/public/localproject"><img src="/start.moiro/public/img/moirolocal.gif" title = "локальные проекты" /></a>
</div>  
